---
    
- hosts: jupyterhub_hosts
  remote_user: root
  roles:
    - common
    - python
    - { role: newrelic, when: newrelic_license_key is defined and newrelic_license_key != ''}
    - nginx
    - supervisor
    - saveusers
    - bash
    - jupyterhub
    - nbgrader
